[package]
name = "glouton"
version = "0.1.0"
authors = ["jrx <jerome+git@rouaix.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bastion = "0.4"
actix = "0.10.0"
actix-rt = "1.1" # <-- Runtime for actix