[package]
name = "glouton"
version = "0.1.0"
authors = ["jrx <jerome+git@rouaix.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bastion = "0.4"
anyhow = "1.0.38"
env_logger = "0.8.2"
log = "0.4.14"
